# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapboxNavigationApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxNavigationApp
  pod 'MapboxNavigation', '~> 0.39.0'
end
