# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlacesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlacesApp
  pod 'GooglePlaces', '3.8.0'
  pod 'GoogleMaps', '3.8.0'
end
